module.exports = {
    variables: {
        APPLICATION_CHANNEL_URL: 'APPLICATION_CHANNEL_URL',
        GUILDINFO_CHANNEL_ID: 'GUILDINFO_CHANNEL_ID',
    },
    cache: {
        GUILDINFO_RECRUITMENT_POST: 'GUILDINFO_RECRUITMENT_POST'
    }
}