name: Restart Service

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
jobs:

  build:

    runs-on: self-hosted
    steps:
    - name: restart service
      run: pm2 restart all
