name: Restart Service

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
jobs:

  build:

    runs-on: self-hosted
    steps:
    - name: stop service
      run: pm2 stop all
    - name: npm install
      working-directory: /root/
      run: npm install
    - name: start service
      run: pm2 start all
